image: node:10.13.0

production:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
    - npm install -g @angular/cli
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase deploy --token $FIREBASE_TOKEN
  only:
  - firebase
